displayName=Gielinor Travels
author=willocon
description=A location-based puzzle and time trial plugin for Old School RuneScape.
tags=gielinor,travels,location,puzzle,time,trial,gieliguessr,gielinortravels,gieli,guessr,gieliguesser
plugins=org.willocon.gielinortravels.GielinorTravelsPlugin
build=standard